5-13.`Exception`クラス
=====================

* 全ての例外クラスのスーパークラス。エラーが発生した場合や、`raise`メソッドで例外を発生した時に、このクラスのオブジェクトが生成される

### 例外クラスの自作

```ruby
>> class MyError < RuntimeError; end
=> nil
>> begin
?>   raise MyError
>> rescue => ex
>>   p ex
>> end
#<MyError: MyError>
=> #<MyError: MyError>
```

※Silverで間違えている

## 以下のコードを実行した時の出力結果として正しいものを１つ選択してください。

raise関数によって明示的に例外を発生させることができます。

例題ではString#ascii_only?を使いテキストにASCII文字以外が使われている場合には例外を発生させています。

ASCII文字は、アルファベット、数字、記号

```ruby
[sample.txtの内容]
Ruby Association
ルビーアソシエーション
るびー
Ruby on Rails

# 解答
>> class NonasciiError < StandardError
>> end
=> nil
>>
?> File.open("sample.txt") do |io|
?>   io.each_line do |str|
?>     begin
?>       raise(NonasciiError, "non ascii character detected") unless str.ascii_only?
>>     rescue => ex
>>       puts "#{ex.message} : #{str}"
>>     end
>>   end
>> end
non ascii character detected : ルビーアソシエーション
non ascii character detected : るびー
=> #<File:sample.txt (closed)>
```

***

### エラーメッセージを指定する

```ruby
>> class MyError < RuntimeError; end
=> nil
>> begin
>>   raise MyError.exception('エラーが発生しました。')
>> rescue => ex
>>   p ex
>> end
#<MyError: エラーが発生しました。>
=> #<MyError: エラーが発生しました。>
```

***

### エラーメッセージを取得する

* `message`、`to_s`、`to_str`：例外オブジェクトに設定されているエラーメッセージを取得

* オブジェクトにエラーメッセージを設定するには、`new`、`exception`メソッドの呼び出し時に引数で指定

```ruby
>> class MyError < RuntimeError; end
=> nil
>> begin
?>   raise MyError.exception('エラーが発生しました。')
>> rescue => ex
>>   p ex.message
>> end
"エラーが発生しました。"
=> "エラーが発生しました。"
```

***

### バックトレースを取得

* `backtrace`：発生した例外のバックトレース情報を取得。これらは、配列で返る。

```ruby
>> class MyError < RuntimeError; end
=> nil
>> begin
?> raise MyError.exception('エラーが発生しました。')
>> rescue => ex
>> p ex.backtrace
>> end
["(irb):41:in `irb_binding'", "/Users/MacUser/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/workspace.rb:87:in `eval'",] # 省略
=> ["(irb):41:in `irb_binding'", "/Users/MacUser/.rbenv/versions/2.4.1/lib/ruby/2.4.0/irb/workspace.rb:87:in `eval'",] # 省略
>>
```

***

### バックトレースを取得(オリジナルの情報追加)

* `set_backtrace`：バックトレース情報にオリジナルの情報を設定する。ただし、それまでのバックトレース情報は上書きされることに注意。

```ruby
>> class MyError < RuntimeError; end
=> nil
>> begin
?>   raise MyError.exception('エラーが発生しました。')
>> rescue => ex
>>   ex.set_backtrace("This is new backtrace.")
>>   p ex.backtrace
>> end
["This is new backtrace."]
=> ["This is new backtrace."]
```

※Silverで間違えている

`StandardError`を継承しないクラスのインスタンスを`raise`メソッドの引数に指定すると、
`TypeError`が発生し、メッセージが表示されます。

* `TypeError`：メソッドの引数に期待される型ではないオブジェクトや、期待される振る舞いを持たないオブジェクトが渡された時に発生します。
  →`StandardError`の下のクラス

```ruby
>> raise ['Error Message']
TypeError: exception class/object expected
```


`rescue`節において例外型を省略すると、`StandardError`とそのサブクラス例外を捕捉する。

`TypeError`は`StandardError`のサブクラスなので、前の行の`rescue`節で処理される

```ruby
>> err = TypeError.new
=> #<TypeError: TypeError>
>> err.class
=> TypeError
>> err.class.superclass
=> StandardError
>> err.class.superclass.superclass
=> Exception
```
